[package]
name = "starter"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm-core = "0.7"
risc0-zkvm-host = "0.7"
risc0-zkvm-serde = "0.7"
serde = "1.0"
tempfile = "3.3"
